version: '3'
services:
  postgres:
    image: 'postgres:9.6.10'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  ecom-api:
    depends_on:
      - "postgres"
    restart: 'no'
    build: .
    volumes:
      - /etc/secret-volume:/etc/secret-volume
    ports:
      - 8080:8080
    environment:
      ECOM_APP_PORT: 8080
      ECOM_PG_HOST: postgres
      ECOM_PG_PORT: 5432
      ECOM_PG_USER: postgres
      ECOM_PG_PASSWORD: postgres
      ECOM_PG_DATABASE: ecom_dev
      ECOM_PG_SSLMODE: disable
      ECOM_PG_CONNECT_TIMEOUT: 30
      ECOM_GOOGLE_PROJECT_ID: test-spycameracctv
      ECOM_GOOGLE_CREDENTIALS: /etc/secret-volume/service_account_credentials/test-spycameracctv-firebase-adminsdk-b06ml-46cd9030e2.json
