#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
schemadir=$DIR/../schema

cat $schemadir/init.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/schema_version_function.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/product.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/inventory.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/shipping_tariff.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/product_set.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/product_set_item.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/cart.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/cart_product.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/price_list.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/price.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/image.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/category.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/product_category.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/category_leaf.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/promo_rule.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/coupon.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/cart_coupon.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/offer.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/usr.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/usr_devkey.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/address.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/order.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/order_item.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/payment.sql | psql --no-psqlrc ecom_dev > /dev/null
cat $schemadir/webhook.sql | psql --no-psqlrc ecom_dev > /dev/null
